# Ansible inventory created from ['/workspaces/panug2024/netlab/topology.yml', 'package:topology-defaults.yml']
#

hosts:
  isp1:
    ipv4:
    - 10.0.0.3
    - 169.254.100.1
    - 172.16.2.3
  isp2:
    ipv4:
    - 10.0.0.4
    - 169.254.200.1
    - 172.16.3.4
  r1:
    ipv4:
    - 10.0.0.1
    - 10.1.0.1
    - 169.254.100.2
    - 172.16.0.1
  r2:
    ipv4:
    - 10.0.0.2
    - 10.1.0.2
    - 169.254.200.2
    - 172.16.1.2
  remote_host1:
    ipv4:
    - 172.16.2.7
  remote_host2:
    ipv4:
    - 172.16.3.8
  server1:
    ipv4:
    - 172.16.0.5
  server2:
    ipv4:
    - 172.16.1.6
netlab_name: netlab
netlab_provider: clab
paths_collect:
  dirs:
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/ansible/tasks/fetch-config
paths_custom:
  dirs:
  - /workspaces/panug2024/netlab
  - /root/.netlab
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/extra
  files:
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''-'' + node_provider + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.cfg'' }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + ansible_network_os +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''.'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''.'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config }}'
  - '{{ custom_config + ''.j2'' }}'
  tasks:
  - '{{ custom_config }}/deploy-{{ inventory_hostname }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}.yml'
  - '{{ custom_config }}/deploy.yml'
paths_deploy:
  dirs:
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/ansible/tasks
  files:
  - '{{ netlab_device_type }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ netlab_device_type }}/{{ config_module }}.yml'
  - deploy-config/{{ netlab_device_type }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - '{{ ansible_network_os }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ ansible_network_os }}/{{ config_module }}.yml'
  - deploy-config/{{ ansible_network_os }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
  tasks_generic:
  - deploy-config/{{ netlab_device_type }}-{{ node_provider }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - deploy-config/{{ ansible_network_os }}-{{ node_provider }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
paths_plugin:
- /workspaces/panug2024/netlab
- /root/.netlab
- /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/extra
paths_ready:
  dirs:
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/ansible/tasks/readiness-check
  files:
  - '{{netlab_device_type}}-{{provider|default(netlab_provider)}}.yml'
  - '{{netlab_device_type}}.yml'
  - '{{ansible_network_os}}-{{provider|default(netlab_provider)}}.yml'
  - '{{ansible_network_os}}.yml'
paths_t_files:
  files:
  - '{{config_module}}/{{netlab_device_type}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{netlab_device_type}}.j2'
  - '{{config_module}}.{{netlab_device_type}}.j2'
  - '{{config_module}}/{{ansible_network_os}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{ansible_network_os}}.j2'
  - '{{config_module}}.{{ansible_network_os}}.j2'
  - '{{netlab_device_type}}/{{config_module}}.j2'
paths_templates:
  dirs:
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/ansible/templates
  - /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/daemons
paths_validate:
- /usr/local/python/3.9.19/lib/python3.9/site-packages/netsim/validate
pools:
  isp1:
    ipv4: 169.254.100.0/24
    prefix: 30
  isp2:
    ipv4: 169.254.200.0/24
    prefix: 30
  l2only: {}
  lan:
    ipv4: 172.16.0.0/16
    prefix: 24
  loopback:
    ipv4: 10.0.0.0/24
    prefix: 32
  mgmt:
    ipv4: 192.168.121.0/24
    mac: 08-4F-A9-00-00-00
    prefix: 24
    start: 100
  p2p:
    ipv4: 10.1.0.0/16
    prefix: 30
  router_id:
    ipv4: 10.0.0.0/24
    prefix: 32
  vrf_loopback:
    ipv4: 10.2.0.0/24
    prefix: 32
