# Ansible inventory created from ['/workspaces/panug2024/netlab/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65001
  community:
    ebgp:
    - standard
    - large
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  neighbors:
  - activate:
      ipv4: true
    as: 65001
    ipv4: 10.0.0.1
    name: r1
    type: ibgp
  - activate:
      ipv4: true
    as: 64513
    ifindex: 2
    ipv4: 169.254.200.1
    name: isp2
    type: ebgp
  next_hop_self: true
  originate:
  - 5.0.0.0/24
  router_id: 10.0.0.2
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/r2/daemons:/etc/frr/daemons
  - clab_files/r2/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- device_config/r2.j2
hostname: clab-netlab-r2
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.2/30
  linkindex: 1
  mtu: 1500
  name: r2 -> r1
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.1/30
    node: r1
  ospf:
    area: 0.0.0.0
    bfd: true
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 169.254.200.2/30
  linkindex: 3
  mtu: 1500
  name: r2 -> isp2
  neighbors:
  - ifname: eth1
    ipv4: 169.254.200.1/30
    node: isp2
  pool: isp2
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: netlab_5
  ifindex: 3
  ifname: eth3
  ipv4: 172.16.1.2/24
  linkindex: 5
  mtu: 1500
  name: r2 -> server2
  neighbors:
  - ifname: eth1
    ipv4: 172.16.1.6/24
    node: server2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.2/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
module:
- bgp
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.2
