# Ansible inventory created from ['/workspaces/panug2024/netlab/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
bgp:
  advertise_loopback: true
  as: 65001
  community:
    ebgp:
    - standard
    - large
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  neighbors:
  - activate:
      ipv4: true
    as: 65001
    ipv4: 10.0.0.2
    name: r2
    type: ibgp
  - activate:
      ipv4: true
    as: 64512
    ifindex: 2
    ipv4: 169.254.100.1
    name: isp1
    type: ebgp
  next_hop_self: true
  originate:
  - 5.0.0.0/24
  router_id: 10.0.0.1
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/r1/daemons:/etc/frr/daemons
  - clab_files/r1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- device_config/r1.j2
hostname: clab-netlab-r1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.1/30
  linkindex: 1
  mtu: 1500
  name: r1 -> r2
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.2/30
    node: r2
  ospf:
    area: 0.0.0.0
    bfd: true
    network_type: point-to-point
    passive: false
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 169.254.100.2/30
  linkindex: 2
  mtu: 1500
  name: r1 -> isp1
  neighbors:
  - ifname: eth1
    ipv4: 169.254.100.1/30
    node: isp1
  pool: isp1
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: netlab_4
  ifindex: 3
  ifname: eth3
  ipv4: 172.16.0.1/24
  linkindex: 4
  mtu: 1500
  name: r1 -> server1
  neighbors:
  - ifname: eth1
    ipv4: 172.16.0.5/24
    node: server1
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: true
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.1/32
  neighbors: []
  ospf:
    area: 0.0.0.0
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
module:
- bgp
- ospf
mtu: 1500
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  router_id: 10.0.0.1
