name: CI
on:
  push:
    branches: [ main , dev_1 ]
  pull_request:
    branches: [ main, dev_1 ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Run Ansible on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: checkout-panug
        uses: actions/checkout@v2
        run: |
          export ANSIBLE_CONFIG=ansible.cfg
          bash ./setup.sh
        working-directory: /home/runner/work/panug2024

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-artifacts
          path: netlab/config

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Get current date and time
        id: date-time
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Add Device Configurations
        run: |
          cd ${{ github.workspace }}
          echo "/*" >> .gitignore
          echo "/*/" >> .gitignore
          echo \!"/netlab/config/" >> .gitignore
          git add -f ${{ github.workspace }}/netlab/config/.
          git commit -m "Config from Runner $CURRENT_DATETIME"
          git branch runner_config_$CURRENT_DATETIME
          git checkout runner_config_$CURRENT_DATETIME
          git push --set-upstream origin runner_config_$CURRENT_DATETIME
          git push origin runner_config_$CURRENT_DATETIME

