name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  Ansible-Run-Ubuntu:
    name: Run Ansible on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run:

      - name: checkout-panug
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install packages
        run: |
          cd ${{ github.workspace }}
          chmod +x setup.sh
          ./setup.sh
          make install

      - name: lint
        run: make lint

      - name: format
        run: make format

